version: "3.7"
services:
  telegram:
    container_name: messenger-bot
    build:
      context: "."
    volumes:
      - ./:/messenger-bot
    ports:
      - 3003:3003

networks:
  default:
    name: IDSA_default
# networks:
#   default:
#     external: fa
#     name: blipconnection_default
